### PR TITLE
github logo

### PR DESCRIPTION
**Pull request by RashiSingh20**

### CODE REVIEW

**Comment by RashiSingh20** [comment]
#5 Kindly check the PR. 
Screenshot (1615)

**Comment by Prerna-0202** [comment]
Hey @RashiSingh20 , Can you please change the logo to this one?
Screenshot (773)

**Comment by RashiSingh20** [comment]
Please check the recent commit #5

**Review by Prerna-0202 — APPROVED** [review]
Great @RashiSingh20

**Pull request merged**
